# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [12]:
import numpy as np

s=0
grades = [77, 85, 56, 90, 66]
for i in grades:
    s=s+i
avg=s/len(grades)

print("Average={0:8.2f}, sum={1:6.0f}".format(s/len(grades),s))


Average=   74.80, sum=   374


### 【示範】陣列導向

In [3]:
import numpy as np
grades = [77, 85, 56, 90, 66]
arr=np.array(grades)
print("max={0:5.2f}, min={1:5.2f}, average={2:5.2f}, std={3:5.2f}".format(np.max(grades),arr.min(),np.average(arr),arr.std()))


max=90.00, min=56.00, average=74.80, std=12.42


最大值

In [4]:
import numpy as np
grades = [77, 85, 56, 90, 66]
arr=np.array(grades)
print("max={0:5.2f}, min={1:5.2f}, average={2:5.2f}, std={3:5.2f}".format(np.max(grades),arr.min(),np.average(arr),arr.std()))


max=90.00, min=56.00, average=74.80, std=12.42


標準差

In [ ]:
import numpy as np
grades = [77, 85, 56, 90, 66]
arr=np.array(grades)
print("max={0:5.2f}, min={1:5.2f}, average={2:5.2f}, std={3:5.2f}".format(np.max(grades),arr.min(),np.average(arr),arr.std()))


12.416118556135006

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [ ]:
prices = [1096.95, 596.95, 896.95]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [17]:
prices = [1096.95, 596.95, 896.95]
rate=31.71 
price=rate*np.array(prices)
#price
#print("NTD Price {0:7.2f}".format(price))
print("NTD Price",price)

NTD Price [34784.2845 18929.2845 28442.2845]


哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [17]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

這還不是我們要的最終成績啊!

In [5]:
import numpy as np
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])
weights*grades


array([17. , 24.5, 36. ])

### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


In [10]:
weights_grades=weights*grades
weights_grades.sum()


np.float64(77.5)

### 【技巧】 一行完成成績計算

In [ ]:
import numpy as np
grades = np.array([10,20,30])
weights = np.array([0.1, 0.1, 0.1])
np.dot(weights,grades)


np.float64(6.0)

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [13]:
a=np.random.rand(50)
a


array([0.98942787, 0.33526446, 0.33230512, 0.11964193, 0.11715589,
       0.73606119, 0.08063412, 0.85096457, 0.00751018, 0.83652685,
       0.85824358, 0.45129613, 0.32650833, 0.43385279, 0.11514271,
       0.76831818, 0.63732747, 0.85659326, 0.83004613, 0.34295258,
       0.65122864, 0.77367769, 0.51918358, 0.41569629, 0.14383704,
       0.06105848, 0.57517534, 0.99431447, 0.23373883, 0.40323367,
       0.85403673, 0.61210641, 0.83103296, 0.75845466, 0.75017809,
       0.98059945, 0.29749988, 0.61981364, 0.06862988, 0.0652879 ,
       0.75123138, 0.28422833, 0.35313893, 0.31071895, 0.98188406,
       0.23864811, 0.51329189, 0.02712132, 0.54413654, 0.97702728])

(10,)

### 【技巧】 檢查 A 的 `shape`

In [18]:
np.shape(a)

(50,)

### 【技巧】 更改 A 的 shape

In [21]:
a.shape=(5,10)
a


array([[0.98942787, 0.33526446, 0.33230512, 0.11964193, 0.11715589,
        0.73606119, 0.08063412, 0.85096457, 0.00751018, 0.83652685],
       [0.85824358, 0.45129613, 0.32650833, 0.43385279, 0.11514271,
        0.76831818, 0.63732747, 0.85659326, 0.83004613, 0.34295258],
       [0.65122864, 0.77367769, 0.51918358, 0.41569629, 0.14383704,
        0.06105848, 0.57517534, 0.99431447, 0.23373883, 0.40323367],
       [0.85403673, 0.61210641, 0.83103296, 0.75845466, 0.75017809,
        0.98059945, 0.29749988, 0.61981364, 0.06862988, 0.0652879 ],
       [0.75123138, 0.28422833, 0.35313893, 0.31071895, 0.98188406,
        0.23864811, 0.51329189, 0.02712132, 0.54413654, 0.97702728]])

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [22]:
a.reshape(10,5)

array([[0.98942787, 0.33526446, 0.33230512, 0.11964193, 0.11715589],
       [0.73606119, 0.08063412, 0.85096457, 0.00751018, 0.83652685],
       [0.85824358, 0.45129613, 0.32650833, 0.43385279, 0.11514271],
       [0.76831818, 0.63732747, 0.85659326, 0.83004613, 0.34295258],
       [0.65122864, 0.77367769, 0.51918358, 0.41569629, 0.14383704],
       [0.06105848, 0.57517534, 0.99431447, 0.23373883, 0.40323367],
       [0.85403673, 0.61210641, 0.83103296, 0.75845466, 0.75017809],
       [0.98059945, 0.29749988, 0.61981364, 0.06862988, 0.0652879 ],
       [0.75123138, 0.28422833, 0.35313893, 0.31071895, 0.98188406],
       [0.23864811, 0.51329189, 0.02712132, 0.54413654, 0.97702728]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [24]:
a.ravel
a

array([[0.98942787, 0.33526446, 0.33230512, 0.11964193, 0.11715589,
        0.73606119, 0.08063412, 0.85096457, 0.00751018, 0.83652685],
       [0.85824358, 0.45129613, 0.32650833, 0.43385279, 0.11514271,
        0.76831818, 0.63732747, 0.85659326, 0.83004613, 0.34295258],
       [0.65122864, 0.77367769, 0.51918358, 0.41569629, 0.14383704,
        0.06105848, 0.57517534, 0.99431447, 0.23373883, 0.40323367],
       [0.85403673, 0.61210641, 0.83103296, 0.75845466, 0.75017809,
        0.98059945, 0.29749988, 0.61981364, 0.06862988, 0.0652879 ],
       [0.75123138, 0.28422833, 0.35313893, 0.31071895, 0.98188406,
        0.23864811, 0.51329189, 0.02712132, 0.54413654, 0.97702728]])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 【技巧】 都是 1 的 array

In [34]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 【技巧】單位矩陣

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [38]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

### 【技巧】`range` 的 array 版

就是 `arange`。

In [41]:
np.arange(1,3,1)

array([1, 2])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [5]:
import numpy as np
A=np.arange(10)
A
B=A.reshape(2,5)
B


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [10]:
B.sum(axis=0)

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [3]:
import numpy as np
C=np.arange(10)
C
C=C.reshape(2,5)
C
Axis0=C.sum(axis=0)
Axis0
C
Axis1=C.sum(axis=1)
Axis1





array([10, 35])

### 【提示】當然也有可能全部算

In [54]:
A.sum()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [55]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [56]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

In [9]:
L = np.array([3, -2, -1, 5, 7, -3])
L>0

array([ True, False, False,  True,  True, False])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [25]:
c=np.array([ True, False, False,  True,  True, False])

c


array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [17]:
L>0
L=L[L>0]
L


array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [7]:
import numpy as np
arr=np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【技巧】2維陣列切法

記得先列後行!

In [13]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

要所有的row, 切出行 1-3 位置。

In [14]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的行col, 切出第 1 列row!

In [40]:
import numpy as np
x=np.arange(10)
x
y=x.reshape(2,5)
y
y[1,:]




array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [ ]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

X=np.c_[x,y]
X

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [48]:
Y=np.r_[x,y]
Y


array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)